### PR TITLE
Fix ProfileCommand and UserProfilePanel updating bug

### LINKED ISSUE #108: Update profile UI when profile command is run

### PR DESCRIPTION
**Pull request by FabianHeng**
Fixes #108

### CODE REVIEW

File: src/main/java/seedu/address/ui/UserProfilePanel.java [hunk 1]
```diff
@@ -36,58 +28,30 @@ public class UserProfilePanel extends UiPart<Region> {
...
     }
 
     /**
      * Initializes and sets user profile data in the UI.
      */
     private void initializeUserProfile() {
         nameLabel.setText("Welcome, " + userProfile.getName().fullName);
+        nameLabel.setMaxWidth(500);
+        nameLabel.setWrapText(false);
+        nameLabel.setTextOverrun(OverrunStyle.ELLIPSIS);
```
Comment (leedeen01) [inline src/main/java/seedu/address/ui/UserProfilePanel.java:47]: I like how you handled text overflow

**Review by leedeen01 — APPROVED** [review]
LGTM.
